### ISSUE TITLE
Will this library support user specified redis database number?

### ISSUE THREAD

**Issue by foresightyj** [FoundatioFx/Foundatio.Redis#15]
In this lib, redis database are by default 0. In `RedisCacheClientOptions`, we can only supply a multiplexer instead of a specific `StackExchange.Redis.IDatabase`.

```
        private IDatabase Database => _options.ConnectionMultiplexer.GetDatabase();
```

In my case, I have several environments (staging, test, dev) all using the same redis server. Each env is assigned a different redis database number.

**Comment by niemyjski** [comment]
You should be able to specify it via the connection string with `defaultDatabase=1` (https://stackexchange.github.io/StackExchange.Redis/Configuration.html) Can you try this.

**Comment by foresightyj** [comment]
@niemyjski Thanks for the reply. You are totally right. I didn't know the connection string trick.

But I do have another related concern. I am interested in the HybridRedisCacheClient. But the pubsub channel is also hard coded as 

https://github.com/FoundatioFx/Foundatio.Redis/blob/10c51b6eecf058601d49ad86b93b0e9958d4aafe/src/Foundatio.Redis/Cache/RedisHybridCacheClient.cs#L16

Since redis channel is not related to database no, different envs in my case will be on the same pubsub channel thus interfering each other.

**Comment by niemyjski** [comment]
You could make this an option via a pr. Aren't channels per database and not shared across? If so, this should just work.

**Comment by foresightyj** [comment]
@niemyjski  Sorry for the late reply. Just came back to work from National Day of China.

![image](https://user-images.githubusercontent.com/1296736/66365414-6db34000-e9bf-11e9-8abf-b66f1a167c5f.png)

As per redis doc, channels are not related to database no. I will see if I could make time for a PR. Thanks for your kind reply.

**Comment by niemyjski** [comment]
Thanks for the clarification, it should be an easy change if you need any help please let us know.

**Comment by foresightyj** [comment]
Aside from the connection string trick, it might be more idiomatic to use the `ConnectionMultiplexer.Connect(ConfigurationOptions opts)` overload.

![image](https://user-images.githubusercontent.com/1296736/66890259-13962880-f018-11e9-927d-168459d46698.png)

**Comment by niemyjski** [comment]
I believe this issue is now resolved via the pr above.
