### ISSUE TITLE
Documentation for usage

### ISSUE THREAD

**Issue by Telavian** [FoundatioFx/Foundatio.Redis#72]
The code is obviously opensource and I likely could figure it all out with some trouble. However I was wondering what is the "path" a message follows from beginning to end? For instance if there was stuck messages or a problem then how would I go about diagnosing this?

What does each general key pattern mean?

Also does it matter if every connection and every queue has maintenance turned on? When can it be turned off?
What does it even do?

**Comment by niemyjski** [comment]
Thanks for reaching out. Can you please provide a little more context for your first two questions. Are you referring about queues, cache client, or storage. 

For your last question about queues, We try and take out a maintenance lock using the CacheLockProvider, Although we'd recommend only running the maintenance on background jobs (so your web processes are also not fighting for locks and doing extra work).

**Comment by Telavian** [comment]
Thanks. I am lastly wondering about the keys.

For instance if I publish a message to queue "TestQueue" then what keys should I expect before publish, after publish, and after consume.

**Comment by niemyjski** [comment]
I'm not sure off the top of my head without digging into the code again but you could debug one of our simple unit tests and then run `keys *` from the redis cli after each breakpoint. There would be at least one list prefixed with something like `q:TestQueue:` with items in it. This would give you a full list of keys.

**Comment by Telavian** [comment]
ok. Thanks.
