### ISSUE TITLE
ReplaceIfEqualAsync sets a wrong expiration value causing RenewAsync to release locks

### ISSUE THREAD

**Issue by syntx** [FoundatioFx/Foundatio.Redis#73]
After noticing an issue with `CacheLockProvider` where `RenewAsync` was causing locks to be released unexpectedly,
I followed the root cause to a line in `RedisCacheClient`:
https://github.com/FoundatioFx/Foundatio.Redis/blob/4212c67514825db74625f0fa2eb4f08c670ad5fe/src/Foundatio.Redis/Cache/RedisCacheClient.cs#L397

**The expiration argument should be sent to the script here in milliseconds and not in seconds.**

i.e. the last argument should be: `expires = expiresIn.Value.TotalMilliseconds`

This is backed by the code in ReplaceIfEqual.lua - where the lua code calls the redis SET command with the PX option used for milliseconds.

I'm unable to push a proper pull request at this time. Perhaps this could be picked up by someone else.

Note that there's a list of additional Lua scripts in `RedisCacheClient.LoadScriptsAsync` that may or may not suffer from a similar issue, I didn't have the time to look into that.

**Comment by ejsmith** [comment]
@syntx I just checked the Redis docs to be sure and the expire values is in seconds not milliseconds.

Lua script is calling `expire <key> <seconds>`
https://github.com/FoundatioFx/Foundatio.Redis/blob/master/src/Foundatio.Redis/Scripts/IncrementWithExpire.lua#L4

Redis expire command:
https://redis.io/commands/expire

I'm not seeing the `PX` option you are talking about.

**Comment by syntx** [comment]
@ejsmith, this is the correct script line that is being called from `ReplaceIfEqualAsync` and not the one you mentioned:
https://github.com/FoundatioFx/Foundatio.Redis/blob/4212c67514825db74625f0fa2eb4f08c670ad5fe/src/Foundatio.Redis/Scripts/ReplaceIfEqual.lua#L4

And this is the relevant Redis command:
https://redis.io/commands/set

I saw this issue when creating a lock with a 1 minute lifetime using the Redis MONITOR command to see what is happening:
Initially, a SET command for 60 seconds was sent to Redis, then, when I renewed the lock - a second SET command for only 60 milliseconds (instead of 60000) was sent causing the lock to expire prematurely!

**Comment by niemyjski** [comment]
@syntx Thanks for the great find, sorry you ran into this. I've created a PR can you both review it: https://github.com/FoundatioFx/Foundatio.Redis/pull/74

Also It looks like dequeue id had the same problem. I also noticed that our ReplaceIfEqualAsync base unit tests doesn't check expiration but I didn't have time to rework that.

**Comment by ejsmith** [comment]
@syntx great find! We will get this fixed ASAP. Thank you!
