### ISSUE TITLE
Redis - Remove by prefix should always provide the keys as input argument

### ISSUE THREAD

**Issue by JulienDeroff** [FoundatioFx/Foundatio.Redis#78]
According to the official documentation:
https://redis.io/commands/eval/

> Important: to ensure the correct execution of scripts, both in standalone and clustered deployments, all names of keys that a script accesses must be explicitly provided as input key arguments. The script should only access keys whose names are given as input arguments. Scripts should never access keys with programmatically-generated names or based on the contents of data structures stored in the database.

Symptom that lead to looking into that:
Trying to remove ~10 000 keys by prefix silently failed.

**Comment by niemyjski** [comment]
Thanks for logging an issue, would you mind submitting a pr for a test and a proposed solution? I'm not sure what we would do for delete by prefix if we have to specify all the keys.  

@ejsmith

**Comment by JulienDeroff** [comment]
The pull request was submitted: https://github.com/FoundatioFx/Foundatio.Redis/pull/79

**Comment by ejsmith** [comment]
@JulienDeroff it seems like the script approach should be more efficient. Can you give more details about what it did? There were 10k keys that should've matched and it didn't delete all of them? Is it possible that new keys are being created while it's running and just the new ones didn't get picked up?

**Comment by ejsmith** [comment]
@JulienDeroff ??

**Comment by JulienDeroff** [comment]
The issue is fairly simple to reproduce: the PR adds a test that fails with the current code and passes in the PR.

The approach taken is not as efficient, as you mention, since it requires two calls instead of one but it fixes the issue.

**Comment by niemyjski** [comment]
@JulienDeroff can you please respond to this part: Can you give more details about what it did? There were 10k keys that should've matched and it didn't delete all of them? Is it possible that new keys are being created while it's running and just the new ones didn't get picked up?

**Comment by JulienDeroff** [comment]
@niemyjski 
The symptom is a silent failure: none of the matching 10k keys are removed. 
The keys were not being created while running the command.
In the test I added, we could add an assertion to make sure all expected keys are existing.

**Comment by niemyjski** [comment]
Fixed by https://github.com/FoundatioFx/Foundatio.Redis/pull/79 Thanks again for the PR! We are working towards getting new releases out after some storage improvements are addressed
